import { useEffect, useState, type FormEvent } from "react";
import { Star } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { saveReview, subscribeToReviews } from "../lib/reviews";
import type { ServerReview } from "../types";
import Button from "./Button";
const FIELDS=["fun","moderation","educational","shopTrust"] as const;
const LABELS={fun:"Fun",moderation:"Moderation",educational:"Educational",shopTrust:"Shop trust"};
export default function ServerReviews({serverId}:{serverId:string}){const{user}=useAuth();const[reviews,setReviews]=useState<ServerReview[]>([]);const[ratings,setRatings]=useState({fun:5,moderation:5,educational:5,shopTrust:5});const[text,setText]=useState("");const[msg,setMsg]=useState("");useEffect(()=>subscribeToReviews(serverId,setReviews),[serverId]);const avg=reviews.length?reviews.reduce((s,r)=>s+(r.fun+r.moderation+r.educational+r.shopTrust)/4,0)/reviews.length:0;async function submit(e:FormEvent){e.preventDefault();if(!user)return;try{await saveReview(serverId,{authorId:user.uid,authorName:user.displayName??"Player",...ratings,text});setText("");setMsg("Review saved.");}catch{setMsg("Unlock this server's join code before reviewing.");}}return <section className="mt-6 rounded-2xl border border-border bg-surface p-6"><div className="flex items-center justify-between"><h2 className="font-mono font-bold text-white">Player reviews</h2><span className="flex items-center gap-1 text-amber-300"><Star size={15} fill="currentColor"/>{avg.toFixed(1)} <small className="text-white/30">({reviews.length})</small></span></div>{user&&<form onSubmit={submit} className="mt-5 rounded-xl bg-surface-2 p-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{FIELDS.map(field=><label key={field} className="text-xs text-white/50">{LABELS[field]}<select value={ratings[field]} onChange={e=>setRatings({...ratings,[field]:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-border bg-surface px-2 py-2 text-white">{[5,4,3,2,1].map(n=><option key={n}>{n}</option>)}</select></label>)}</div><textarea required minLength={10} maxLength={500} value={text} onChange={e=>setText(e.target.value)} placeholder="Share your experience…" className="mt-3 w-full rounded-xl border border-border bg-surface px-3 py-3 text-sm text-white"/><Button type="submit" size="sm">Post review</Button>{msg&&<span className="ml-3 text-xs text-cyan-300">{msg}</span>}</form>}<div className="mt-5 space-y-4">{reviews.slice(0,8).map(review=><div key={review.id} className="border-t border-border pt-4"><div className="flex justify-between"><strong className="text-sm text-white">{review.authorName}</strong><span className="text-xs text-amber-300">★ {((review.fun+review.moderation+review.educational+review.shopTrust)/4).toFixed(1)}</span></div><p className="mt-1 text-sm text-white/60">{review.text}</p></div>)}</div></section>}
